title: Beiqi Wang's Homepage
page-top-title: Beiqi
top-section-bg-text: Artificial Intelligence
home-subtitle: Beiqi Wang&ensp;|&ensp;Thiago&ensp;|&ensp;王贝琦
copyright-text: '&copy; Beiqi Wang 2024-2025.'
